language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - EXECUTE_CS_CHECK=true
        - TEST_COVERAGE=true
        - REQUIRE_VERSION="zf-commons/zfc-rbac:dev-develop"
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - REQUIRE_VERSION="zf-commons/zfc-rbac:^2.5.2"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES
  - composer require $REQUIRE_VERSION

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml; else ./vendor/bin/phpunit; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/docheader check config/ src/ tests/; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
